name: melissab
favicon: null
layout_spectrum: 0.43072680151090026
typography_spectrum: 0.8472820443566889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.37215403257869184
  lightness: 0.471180837135762
  saturation: 0.9055087356828153
  rhythmicContrast: 0.37525483779609203
purpose: []
